### ISSUE TITLE
[Issue] Keep empty attributes assigned pointless empty value

### ISSUE THREAD

**Issue by mikehayesuk** [Swaagie/minimize#15]
When the "keep empty attributes" option is enabled, the compiled HTML actually grows because the attribute is given an empty string value even if it has no value before.

Example, the following:

```
<div translate>Test</div>
```

Is compiled to:

```
<div translate="">Test</div>
```

The use case that applies here is AngularJS directives, though I'm sure there are other use cases for attributes without a value. The issue was originally raised by @udayms here: https://github.com/jonathanepollack/gulp-minify-html/issues/6

Thanks

**Comment by philBrown** [comment]
Has this regressed? I'm seeing this in gulp-minify-html 1.0.3 which uses minimize 1.5.0
