### ISSUE TITLE
white space in attribute is not stripped

### ISSUE THREAD

**Issue by stevemao** [Swaagie/minimize#26]
i have some inline style in my div

```
<div style="margin: 0;
    overflow: hidden;
    width: 100%;
    height: 100%;
    -webkit-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
    background-position: 50% 50%;">
  </div>
```

But after minimize using `gulp-minify-html` the white spaces is still there (it could just make all the attribute values oneline).

**Comment by mlenser** [comment]
This is actually the reason I am going to switch away from this minifier. Any hope of optionally allowing line breaks in attributes? For instance the value of an input.

**Comment by Swaagie** [comment]
As far as I'm aware this was fixed, if you have a example where it does not work please let me know. I'll make sure to fix that as well

**Comment by mlenser** [comment]
The behavior before this bug was fixed is what I desire.

Likely the way to allow for this is to implement ignoring areas between a specified comment.

**Comment by Swaagie** [comment]
Nvm my stupid previous comment, fixed and released with `1.5.0`, simply pass `whitespace: true` to retain all whitespace/newlines

**Comment by mlenser** [comment]
Whitespace in attributes, nice! I will try it out later and report back.

Thanks so much!

**Comment by mlenser** [comment]
Any eta on 1.5?

**Comment by Swaagie** [comment]
1.5 should be out, not sure about the integration with the gulp plugin, but that is outside my control.

`npm info minimize` output

```
     '1.3.3': '2015-04-03T07:17:53.369Z',
     '1.4.0': '2015-04-25T23:30:40.919Z',
     '1.4.1': '2015-04-29T07:26:47.843Z',
     '1.5.0': '2015-07-01T07:37:17.260Z' },
```

**Comment by mlenser** [comment]
I don't see any commits on this GitHub or any releases, which is why I'm asking.

https://github.com/Swaagie/minimize/commits/master
https://github.com/Swaagie/minimize/releases

Gulp is indeed something else and I plan to ask them as soon as I confirm that 1.5 is released. But if you say it is I'll open an issue there for them to use your latest.

**Comment by Swaagie** [comment]
O haha, my bad, I totally forgot to push and tag :( thanks for notifying.
