### ISSUE TITLE
Allow custom htmlparser2 instance

### ISSUE THREAD

**Issue by Swaagie** [Swaagie/minimize#47]
title says it all

**Comment by lloiser** [comment]
try this:
```js
var minimize = new Minimize({ ... });
minimize.htmlparser = ... // insert your htmlparser2 instance here
minimize.parse(...);
```

**Comment by Swaagie** [comment]
haha thanks for the reply, but this was more a mental note for myself ;) Fixed with https://github.com/Moveo/minimize/commit/f95e02dadc4d41fa61285e61281b466255d3fe54. Will release `2.0.0` asap
