### ISSUE TITLE
cli-color version?

### ISSUE THREAD

**Issue by davidbarrows** [Swaagie/minimize#56]
Hi, I already mentioned this to the gulp-minify-html developer who uses "minimize", but then realized the warning I was getting was probably generated because of "minimize" dependency on an older version of cli-color... 

Hi, I realize this is fairly obsessive-compulsive of me, but... I'm trying to tidy up my npm dependencies in a project and notice gulp-minify-html calls for cli-color 0.3.x, but the latest cli-color is 1.0.0. Whenever you get around to it, is it possible you might consider updating your cli-color dependency to cli-color 1.0.0 ? (Please see below)... apologies if this is totally annoying. Just thought I'd ask. Thanks and regards -dB

davids-mbp:dBWeb davidwbarrows$ npm outdated
Package Current Wanted Latest Location
cli-color 0.3.3 0.3.3 1.0.0 cli-color
lodash 2.4.2 2.4.2 3.10.1 lodash
merge-stream 0.1.8 0.1.8 1.0.0 merge-stream
davids-mbp:dBWeb davidwbarrows$ npm update
npm WARN unmet dependency /Users/davidwbarrows/Data/Computing/Angular/dBWeb/node_modules/gulp-minify-html/node_modules/minimize requires cli-color@'0.3.x' but will load

**Comment by Swaagie** [comment]
updated all dependencies, including cli-color. OCD is not always bad ;) haha. Anyways released as `1.7.0`

**Comment by davidbarrows** [comment]
thanks

**Comment by davidbarrows** [comment]
That fixed it, thanks!
