### ISSUE TITLE
Don't remove attribute quotes if value contains `<` or `>`

### ISSUE THREAD

**Issue by rahatarmanahmed** [Swaagie/minimize#62]
```shell
$ minimize '<img src="whatever.png" alt="<cool>">'

  Minimize HTML

  Using content from the CLI
  Minimizing content...
  Finished processing content

  =========================================

<img src=whatever.png alt=<cool>>
```

Removing quotes from that `alt` parameter exposes the angle brackets, screwing up the HTML causing browsers to parse the last `>` as a text node. I could use the option to not remove quotes but it would be nice if it was smart enough to keep quotes if they contain `<` or `>`.

**Comment by Swaagie** [comment]
Thanks for reporting, released with 1.7.2
