### ISSUE TITLE
HTML minification eats up spaces between inline elements

### ISSUE THREAD

**Issue by kilianc** [Swaagie/minimize#66]
```html
<div>Foo <div class="display: inline-block;">Bar</div></div>
```

will yield

```html
<div>Foo<div class="display: inline-block;">Bar</div></div>
```

**Comment by Swaagie** [comment]
This is working as expected as I've got no way to tell if `div` is an inline element. By default `div` is a block level element and should not need flowing spaces. That said there are two fixes possible.

- use an inline `span` inside the `div`. 
- Run minimize with the option `loose: true`, this will increase the overall whitespace a bit, not by much.

**Comment by Swaagie** [comment]
Almost forgot you could also write a plugin that parses the inline styles for the element and determines if it is inline or not, this is beyond the scope of the main project though

**Comment by kilianc** [comment]
Yeah @Swaagie , I think I will use this to write more semantic code, there is no reason to use a div there..
