### ISSUE TITLE
Keep case

### ISSUE THREAD

**Issue by dsebastien** [Swaagie/minimize#74]
Would it be possible to choose whether the minification keeps the case as is?

For example, currently, the following `<li *ngFor ...` will become <li *ngfor ...`.
Given that Angular 2 now has case sensitive templates, this behavior breaks with Angular applications.

Being able to define a sort of "case: true" option would be very useful

**Comment by Swaagie** [comment]
Sorry this is done by the DOMparser of htmlparser2. Changes would have to be made in the parser or a custom parser needs to be supplied.
