### ISSUE TITLE
Stripping off extra HTML tags

### ISSUE THREAD

**Issue by ashishthakur913** [Swaagie/minimize#77]
So i used it for an html file for test and it took off the last </div> tag.

Any solutions?

**Comment by Nogbit** [comment]
I'm sure he would appreciate the source html that you used, otherwise this doesn't help.

**Comment by Swaagie** [comment]
+1 :) Could you provide an example, in most cases this would be a result of htmlparser2 stripping the tag though, which could indicate the HTML was invalid.

**Comment by ashishthakur913** [comment]
Hi, 
So i looked into the code, the problem was that the HTML was invalid. Thank you anyways :)

**Comment by Swaagie** [comment]
Your welcome, glad you got it resolved.
